'use client';
// src/components/report/ResearchReportModal.tsx
// Structured Research Report Builder with live preview, Markdown copy, and Printable PDF Export

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  FileText, Download, Copy, Check, Printer, X, Sparkles,
  BookOpen, ExternalLink, ShieldCheck, Calendar, Share2
} from 'lucide-react';
import { toast } from 'sonner';
import MarkdownMessage from '@/components/chat/MarkdownMessage';
import type { ResearchReport } from '@/types/research';

interface Props {
  report: ResearchReport | null;
  isOpen: boolean;
  onClose: () => void;
  onOpenSource?: (sourceId: string) => void;
}

export default function ResearchReportModal({ report, isOpen, onClose, onOpenSource }: Props) {
  const [activeTab, setActiveTab] = useState<'structured' | 'markdown'>('structured');
  const [copied, setCopied] = useState(false);

  if (!isOpen || !report) return null;

  const generateMarkdownString = () => {
    return `# ${report.topic}
*Unified Intelligence & Research Dossier*
*Generated on: ${new Date(report.generatedAt).toLocaleDateString()}*

---

## 1. Executive Summary
${report.executiveSummary}

## 2. Background & Strategic Context
${report.background || 'Context established across verified local and live internet sources.'}

## 3. Key Research Findings
${report.keyFindings?.map((f, i) => `${i + 1}. ${f}`).join('\n') || 'No findings recorded.'}

## 4. Empirical Evidence & Source Excerpts
${report.evidence?.map((e) => `### ${e.claim}\n${e.sources?.map((s) => `- ${s.text} *(Source: ${s.sourceId})*`).join('\n')}`).join('\n\n') || '—'}

## 5. Perspectives & Stakeholder Analysis
${report.perspectives?.map((p) => `### ${p.viewpoint}\n*Supported by sources: ${p.sources?.join(', ')}*`).join('\n\n') || '—'}

## 6. Identified Contradictions & Tensions
${report.contradictions?.map((c, i) => `${i + 1}. ${c}`).join('\n') || 'No direct contradictions detected.'}

## 7. Key Statistics & Data Points
${report.statistics?.map((s, i) => `${i + 1}. ${s}`).join('\n') || 'No specific numerical statistics extracted.'}

## 8. Strategic Conclusion
${report.conclusion}

## 9. Bibliography of Evaluated Sources
${report.sources?.map((s, i) => `${i + 1}. **${s.title}** (${s.provider}) — [Access Link](${s.url})`).join('\n') || '—'}

---
*Generated by Smart Finder AI Research Workspace*`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdownString());
    setCopied(true);
    toast.success('Research Report copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdownString();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.topic.replace(/[^a-zA-Z0-9]+/g, '-').toLowerCase()}-report.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded as Markdown');
  };

  const handlePrintPDF = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/80 backdrop-blur-md">
      <motion.div
        initial={{ opacity: 0, scale: 0.96 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.96 }}
        className="relative w-full max-w-4xl max-h-[90vh] flex flex-col rounded-3xl shadow-2xl overflow-hidden"
        style={{
          background: 'var(--bg-elevated)',
          border: '1px solid var(--border)',
          boxShadow: '0 25px 60px rgba(0,0,0,0.6), 0 0 0 1px rgba(99,102,241,0.2)',
        }}
      >
        {/* Modal Header */}
        <div className="p-5 flex items-center justify-between border-b border-[var(--border)] flex-shrink-0 bg-[var(--bg-base)]">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl flex items-center justify-center shadow-md"
              style={{ background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)' }}>
              <BookOpen className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white truncate max-w-[450px]">
                {report.topic}
              </h2>
              <p className="text-xs text-zinc-400">
                Formal Research Dossier · {new Date(report.generatedAt).toLocaleDateString()}
              </p>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold bg-[var(--bg-elevated)] border border-[var(--border)] text-zinc-300 hover:text-white transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>

            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold bg-[var(--bg-elevated)] border border-[var(--border)] text-zinc-300 hover:text-white transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Markdown</span>
            </button>

            <button
              onClick={handlePrintPDF}
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-xl text-xs font-bold text-white shadow-md transition-all hover:scale-105"
              style={{
                background: 'linear-gradient(135deg, #6366f1 0%, #06b6d4 100%)',
              }}
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Download PDF</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-xl text-zinc-400 hover:text-white hover:bg-white/10 transition-colors ml-2"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Body: Printable View */}
        <div id="printable-research-report" className="flex-1 overflow-y-auto p-6 sm:p-8 space-y-6 select-text">
          {/* Executive Summary */}
          <div className="p-5 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 space-y-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-400 flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5" /> 1. Executive Summary
            </h3>
            <p className="text-sm leading-relaxed text-zinc-200">
              {report.executiveSummary}
            </p>
          </div>

          {/* Background */}
          {report.background && (
            <div className="space-y-2">
              <h3 className="text-xs font-bold uppercase tracking-wider text-zinc-400">
                2. Strategic Background & Context
              </h3>
              <p className="text-xs leading-relaxed text-zinc-300">
                {report.background}
              </p>
            </div>
          )}

          {/* Key Findings */}
          {report.keyFindings && report.keyFindings.length > 0 && (
            <div className="space-y-2">
              <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-400 flex items-center gap-1.5">
                <ShieldCheck className="w-3.5 h-3.5" /> 3. Key Verified Findings
              </h3>
              <div className="space-y-2">
                {report.keyFindings.map((finding, idx) => (
                  <div
                    key={idx}
                    className="p-3.5 rounded-xl bg-[var(--bg-base)] border border-[var(--border)] text-xs text-zinc-200 leading-relaxed flex items-start gap-2.5"
                  >
                    <span className="w-5 h-5 rounded-md bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-bold text-[10px] flex-shrink-0 mt-0.5">
                      {idx + 1}
                    </span>
                    <span>{finding}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Evidence */}
          {report.evidence && report.evidence.length > 0 && (
            <div className="space-y-2">
              <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-400">
                4. Empirical Evidence & Citations
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {report.evidence.map((ev, idx) => (
                  <div key={idx} className="p-3.5 rounded-xl bg-[var(--bg-base)] border border-[var(--border)] space-y-1.5">
                    <h4 className="text-xs font-bold text-zinc-200">{ev.claim}</h4>
                    {ev.sources && ev.sources.map((s, sIdx) => (
                      <p key={sIdx} className="text-[11px] text-zinc-400 italic">
                        &ldquo;{s.text}&rdquo;
                      </p>
                    ))}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Perspectives */}
          {report.perspectives && report.perspectives.length > 0 && (
            <div className="space-y-2">
              <h3 className="text-xs font-bold uppercase tracking-wider text-purple-400">
                5. Stakeholder Perspectives
              </h3>
              <div className="space-y-2">
                {report.perspectives.map((p, idx) => (
                  <div key={idx} className="p-3 rounded-xl bg-purple-500/10 border border-purple-500/20 text-xs text-purple-200">
                    {p.viewpoint}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Strategic Conclusion */}
          {report.conclusion && (
            <div className="p-4 rounded-2xl bg-indigo-500/15 border border-indigo-500/30 text-xs text-indigo-100 leading-relaxed">
              <span className="font-bold text-indigo-300">Strategic Conclusion: </span>
              {report.conclusion}
            </div>
          )}

          {/* Sources */}
          {report.sources && report.sources.length > 0 && (
            <div className="space-y-2 pt-4 border-t border-[var(--border)]">
              <h3 className="text-xs font-bold uppercase tracking-wider text-zinc-400">
                6. Evaluated Sources & Provenance
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {report.sources.map((src, idx) => (
                  <div
                    key={idx}
                    onClick={() => onOpenSource?.(src.id)}
                    className="p-2.5 rounded-xl bg-[var(--bg-base)] border border-[var(--border)] flex items-center justify-between text-xs cursor-pointer hover:border-indigo-500/40 transition-colors"
                  >
                    <span className="truncate font-medium text-zinc-300">{src.title}</span>
                    <span className="text-[10px] text-indigo-400 flex items-center gap-1 flex-shrink-0 ml-2">
                      <span>{src.provider}</span>
                      <ExternalLink className="w-2.5 h-2.5" />
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
}
